### ISSUE TITLE
对照官方的迁移文档将此工程迁移为mysql时，启动报错（HelloAbp同样也有这个问题）

### ISSUE THREAD

**Issue by cucr** [xiajingren/ABP-vNext-Vue#2]
对照一下文档进行mysql迁移，所有步骤都走完，数据库也成功创建，但是启动host工程时发生异常退出
https://docs.abp.io/zh-Hans/abp/latest/Entity-Framework-Core-MySQL
报错如下，异常不太好分析，求助！！！
2020-10-22 20:30:39.717 +08:00 [INF] Starting Xhznl.HelloAbp.HttpApi.Host.
2020-10-22 20:30:43.223 +08:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during PostConfigureServices phase of the module Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule, Volo.Abp.AspNetCore.Mvc, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<!!0> System.Collections.Generic.AbpListExtensions.SortByDependencies(System.Collections.Generic.IEnumerable`1<!!0>, System.Func`2<!!0,System.Collections.Generic.IEnumerable`1<!!0>>)'.
   at Volo.Abp.AspNetCore.Mvc.ApplicationPartSorter.Sort(ApplicationPartManager partManager, IModuleContainer moduleContainer)
   at Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule.PostConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Xhznl.HelloAbp.Startup.ConfigureServices(IServiceCollection services) in C:\abp\ABP-vNext-Vue-master\aspnet-core\src\Xhznl.HelloAbp.HttpApi.Host\Startup.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Xhznl.HelloAbp.Program.Main(String[] args) in C:\abp\ABP-vNext-Vue-master\aspnet-core\src\Xhznl.HelloAbp.HttpApi.Host\Program.cs:line 27

**Comment by xiajingren** [comment]
ABP-vNext-Vue这个项目后端部分除了数据库链接字符串外没有修改别的东西，建议去abp的issues搜搜有没有类似问题。
